### ISSUE TITLE
Supported file formats for gene list uploads should include `txt`

### ISSUE THREAD

**Issue by kennethbruskiewicz** [broadinstitute/sharpener-gui#52]
TXT files should be supported, and any tab- or comma-delimited format with line breaks should be supported.

@remontoire-pac any additional formats?

**Comment by remontoire-pac** [comment]
The issue I'm having remains. See the attachment. Windows is expecting only
two file types (lower left) so the browse box (middle) shows nothing since
the files I'm looking for are *.txt. If I manually choose all file types,
it accepts the *.txt file, but can you make it one of the defaults along
with *.csv and *.tsv?
____________________________
Paul Clemons
Institute Scientist, Broad Institute
pclemons@broadinstitute.org
+1 (617) 359-9092
____________________________
